/**
 * Core types for the Headlamp SkillBridge Credential library.
 *
 * Design rule enforced here: completion language is structurally unreachable
 * without a supervisor attestation. The `EvidenceBasis` discriminated union
 * has no variant that permits completion wording unless it carries a
 * `SupervisorAttestation` object.
 */

/** ISO 8601 calendar date, e.g. "2026-04-25". */
export type IsoDate = string;

/** ISO 8601 date-time, e.g. "2026-04-25T00:00:00Z". */
export type IsoDateTime = string;

/** Facts established by verified placement documents (offer letter + training plan). */
export interface PlacementDetails {
  /** Name of the SkillBridge host organization, e.g. "CoolSys Inc." */
  hostOrganization: string;
  /** Program start date. */
  startDate: IsoDate;
  /** Program end date. */
  endDate: IsoDate;
}

/**
 * A supervisor's attestation of completion. Constructing one of these is the
 * ONLY way to reach completion language in an assertion.
 */
export interface SupervisorAttestation {
  /** Attesting supervisor's full name. */
  supervisorName: string;
  /** Attesting supervisor's title at the host organization. */
  supervisorTitle: string;
}

/**
 * The evidence basis for a credential. Exactly three states:
 *
 * - `documents`   — placement documents verified; asserts PLACEMENT only.
 * - `attestation` — supervisor attestation on file; asserts COMPLETION.
 * - `both`        — documents AND attestation; asserts placement + completion.
 *
 * The `attestation` and `both` variants require a `SupervisorAttestation`
 * to construct — the type system, not convention, prevents completion
 * claims without attestation input.
 */
export type EvidenceBasis =
  | { basis: 'documents'; placement: PlacementDetails }
  | { basis: 'attestation'; placement: PlacementDetails; attestation: SupervisorAttestation }
  | { basis: 'both'; placement: PlacementDetails; attestation: SupervisorAttestation };

/** Issuer profile embedded in credentials (OBv3 `Profile`). */
export interface IssuerProfile {
  /** Issuer DID, e.g. "did:web:myheadlamp.com". */
  id: string;
  /** Display name, e.g. "Headlamp". */
  name: string;
  /** Optional homepage. */
  url?: string;
}

/** Reference to a slot in a published Bitstring Status List. */
export interface CredentialStatusRef {
  /** URL where the signed status list credential is published. */
  statusListCredential: string;
  /** Index of this credential's bit in the list. */
  statusListIndex: number;
}

/** A JSON-LD document with a proof attached. */
export type SignedCredential = Record<string, unknown> & {
  '@context': unknown;
  id?: string;
  type: string[];
  proof: Record<string, unknown> | Record<string, unknown>[];
};

/** A credential that has been built but not yet signed. */
export type UnsignedCredential = Record<string, unknown> & {
  '@context': unknown;
  type: string[];
};

/** DID document as generated by `buildDidWebDocument`. */
export interface DidDocument {
  '@context': string[];
  id: string;
  verificationMethod: {
    id: string;
    type: 'Multikey';
    controller: string;
    publicKeyMultibase: string;
  }[];
  assertionMethod: string[];
  authentication: string[];
  [key: string]: unknown;
}

/** The three endorsement kinds, each issued as a separate EndorsementCredential. */
export type EndorsementKind = 'work_confirmed' | 'would_hire' | 'was_hired';

/**
 * Single-file offline verification bundle: the credential, the endorsements
 * the HOLDER chose to include, and snapshots of every document verification
 * needs (DID documents, status list credentials). `verifyBundle` passes with
 * zero network access.
 *
 * Display control: `endorsements` contains exactly what the builder was
 * given. There is no hidden/excluded flag anywhere in this format — an
 * excluded endorsement is simply absent.
 */
export interface CredentialBundle {
  format: 'headlamp-credential-bundle';
  version: '0.1';
  credential: SignedCredential;
  endorsements: SignedCredential[];
  didDocuments: DidDocument[];
  statusListCredentials: SignedCredential[];
}

/** Result of verifying a single credential. */
export interface CredentialCheck {
  id: string | undefined;
  signatureVerified: boolean;
  notRevoked: boolean | 'no-status';
  withinValidity: boolean;
  errors: string[];
}

/** Result of verifying a bundle. */
export interface BundleVerificationResult {
  verified: boolean;
  credential: CredentialCheck;
  endorsements: (CredentialCheck & { referencesCredential: boolean; kind?: EndorsementKind })[];
  errors: string[];
}
